### ISSUE TITLE
Computer Engineering VS Information Technology Course

### ISSUE THREAD

**Issue by arma2256** [Hack-with-Github/Awesome-Hacking#11]

**Comment by MacRiada** [comment]
Hacking, information technology and computer engineering are very broad, vague terms that could be taken by a reasonable person to all mean the very same thing. Without knowing what exactly you want to do and what exactly the syllabus of each course it will be very difficult for anyone to answer you.

**Comment by arma2256** [comment]
I am also not able to find syllabus of the course on internet , so i am hoping that someone who has attended the courses might be able to hlep

**Comment by satyam857** [comment]
Refer this link 
http://www.stupidsid.com/study-resources/documents/syllabus
