### ISSUE TITLE
Do we need the word `awesome` in front of every name of the repository? 

### ISSUE THREAD

**Issue by aleksandar-todorovic** [Hack-with-Github/Awesome-Hacking#2]
In my opinion, it just makes the list look clunky and not easily skimmable to find what I want.

**Comment by Chan9390** [comment]
I accept, as the number of lists have been increased it now looks clunky. I have made other plans to make the view even more better.

**Comment by jarrydfillmore** [comment]
Good call!

**Comment by Chan9390** [comment]
As we put links to awesome repositories, we cannot change the name of them. The titles will not be changed. Anyways thanks for your suggestion.

**Comment by Chan9390** [comment]
Hey @aleksandar-todorovic , it seems that people would like to have the word **"awesome"** removed.
![screenshot 18](https://cloud.githubusercontent.com/assets/12944530/20526143/cce74822-b0e8-11e6-83d9-d9d998884d7d.png)

Accepting your pull request ( #5 ).
Thanks for your contribution

**Comment by aleksandar-todorovic** [comment]
You're welcome! :)
