### ISSUE TITLE
Awesome-Hacking logo proposal 

### ISSUE THREAD

**Issue by hawk28** [Hack-with-Github/Awesome-Hacking#37]
Hello, I am a graphic designer. I contribute to open source softwares by designing logos. Do you want me to design a logo for Awesome-Hacking?. I will wait for feedback. Have a nice day!

**Comment by Chan9390** [comment]
I would have a look at it. But I cannot pay.

**Comment by hawk28** [comment]
I will do it for free

**Comment by hawk28** [comment]
did you like it? Is there anywhere you want in your office?
![artboard1111 1](https://user-images.githubusercontent.com/38923402/41822192-69f5a5c2-77f4-11e8-9a47-678204af977a.png)

**Comment by Chan9390** [comment]
Hey, I prefer not to have this conversation in public. I am closing this issue. Please email at `hackwithgithub [at] gmail [dot] com`.

**Comment by forbearing** [comment]
Awesome !!!

**Comment by jbushmaster007** [comment]
GREAT........

**Comment by heenarawal** [comment]
Hey  
I want to share a comic stripe for my blogs can you help me out. It’s only for hacking. If you really want to do ping me on my GitHub.

**Comment by SATYAM9717069261** [comment]
lms.galgotiasuniversity.edu.in
Hey , can you help me find bugs in this website
