### ISSUE TITLE
[Discussion] Awesome Hacking named in a $20 million lawsuit

### ISSUE THREAD

**Issue by petercunha** [Hack-with-Github/Awesome-Hacking#53]
This is pretty interesting news for the repo! This project his been directly referenced in a $20 million class action lawsuit versus Github regarding the recent Captiol One data breach.

The lawsuit, filed on Thursday, asserts that GitHub “actively encourages hacking.” The suit points to a GitHub repository named “**Awesome Hacking**” (that's us 😎) that lists resources for hacking, bug bounties, fuzzing, penetration testing, reverse engineering and more.

**Comment by micxer** [comment]
That should drive the numbers of stars to new highs! 😄

**Comment by nakedpwr** [comment]
Well well... I was unaware of us being a special interest group. I thought this was a singles mixer for neck beards and the personal grooming disadvantaged. Let me shiny up before they get here. Could  i borrow a toothbrush?

**Comment by nakedpwr** [comment]
Addendum: should this be considered more of a bug or an issue one update? I'm trying to file this...  ;)
