### ISSUE TITLE
WOW Hacking GUI

### ISSUE THREAD

**Issue by SpellCasterHax** [Hack-with-Github/Awesome-Hacking#70]
SpellCaster... I came up with it, because hackers are referred to has "Wizards" but im a mage so i cast spells :) anyways...

Im no developer. But there is something that i would like to see come to life in the hacking community... Your Lazy Script is already along the lines of what im wanting to see happen...

In World Of Warcraft you have a gui that allows you to keybind spells that you cast... (similar to pressing "L" to launch lazy script, or "5" to enable anonsurf...

Im wanting a GUI build that is similar to a WOW gui that will allow us to bind commands and then execute these commands to rapidly speed up the hacking process. 

Here are some features that I would like to see:
1. I would like inside the program a text doc on the side where we can pre type our codes as we need them. Then using a drag and drop feature we can drag the commands to 1,2,3,4,5 etc... as we see fit.
2. The terminal window in the middle of our screen should also have the ability to "split" into another terminal window to run separate commands
3. The terminal window should allow for point and click to change values as needed if one forgot to change the "spell"
4. I would like to see a sub spell menu by pressing shift+(spell key) to bring up other commands related to it... For example: 3(Change Mac) Shift+(key)=(r) to change mac address...
5. Having different Spell trees to be able to quickly switch between different hacking methods like: tree1=wifi hacking tree2=website hacking tree3=Nmap...
6. A tab that we can attach man pages for tools to quickly refer to when building our spells
7. A cool list of spell icons to choose from that can be bind to specific spells
8. Ctrl=F to find things within the terminal
9. Auto hyper link to executable links: links, images, file paths etc...
10. Have this able to work with top kali tools, if not all of them...
11. Being able to macro spells would be a huge help too... MUCH FASTER!!

I think this would be really cool and fun tool to have... @arismelachroinos 

I dont know who will be the best person to be able to work on something like this so if anyone else is interested in seeing something like this then feel free to forward this to someone that can...

see attached pic for an better idea of what im envisioning

anyone that starts to work on this hit me up: @SpellCasterHax

![e6036a8f9d28541fd7942288fe5cf1c2](https://user-images.githubusercontent.com/58918154/70869143-15f7fe80-1f45-11ea-9463-85df23bf8f5f.jpg)

**Comment by RenaKunisaki** [comment]
Sounds like you want something along the lines of Awesome window manager.
